# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_3step' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for RxSwift_3step
  


  target 'RxSwift_3stepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift_3stepUITests' do
    # Pods for testing
  end

end
